import { randomUUID } from 'node:crypto';
import { setTimeout as sleep } from 'node:timers/promises';
import { AiProviderUnavailableError, AiTimeoutError } from '../../domain/errors.js';
import type { AiCompletion, AiProvider } from '../../domain/ports/AiProvider.js';

/** The subset of OpenAI's `chat.completion` response object that we simulate. */
interface OpenAiChatCompletion {
  id: string;
  object: 'chat.completion';
  created: number;
  model: string;
  choices: {
    index: number;
    message: { role: 'assistant'; content: string };
    finish_reason: 'stop';
  }[];
  usage: { prompt_tokens: number; completion_tokens: number; total_tokens: number };
}

export interface MockOpenAiProviderOptions {
  minLatencyMs: number;
  maxLatencyMs: number;
  /** Probability between 0 and 1 that a call fails like an upstream 5xx would. */
  failureRate: number;
  timeoutMs: number;
  /** Injectable for deterministic tests. */
  random?: () => number;
  wait?: (ms: number) => Promise<unknown>;
}

const MOCK_MODEL = 'gpt-4o-mini (mocked)';

/**
 * Simulates the OpenAI Chat Completions API: random latency, OpenAI-shaped
 * response and usage numbers, and optional random failures. This is the
 * default provider, as the brief requires a mocked OpenAI response.
 */
export class MockOpenAiProvider implements AiProvider {
  private readonly random: () => number;
  private readonly wait: (ms: number) => Promise<unknown>;

  constructor(private readonly options: MockOpenAiProviderOptions) {
    this.random = options.random ?? Math.random;
    this.wait = options.wait ?? ((ms) => sleep(ms));
  }

  async ask(question: string): Promise<AiCompletion> {
    const { minLatencyMs, maxLatencyMs, timeoutMs, failureRate } = this.options;
    const latencyMs = minLatencyMs + Math.floor(this.random() * (maxLatencyMs - minLatencyMs + 1));

    if (latencyMs > timeoutMs) {
      await this.wait(timeoutMs);
      throw new AiTimeoutError();
    }
    await this.wait(latencyMs);

    if (this.random() < failureRate) {
      throw new AiProviderUnavailableError('Simulated upstream failure from the mocked provider.');
    }

    return toAiCompletion(this.buildCompletion(question));
  }

  private buildCompletion(question: string): OpenAiChatCompletion {
    const preview = question.length > 80 ? `${question.slice(0, 77)}...` : question;
    const content =
      `This is a mocked AI response to your question: "${preview}". ` +
      'In production this answer would be generated by a large language model.';

    const promptTokens = estimateTokens(question);
    const completionTokens = estimateTokens(content);

    return {
      id: `chatcmpl-${randomUUID()}`,
      object: 'chat.completion',
      created: Math.floor(Date.now() / 1000),
      model: MOCK_MODEL,
      choices: [{ index: 0, message: { role: 'assistant', content }, finish_reason: 'stop' }],
      usage: {
        prompt_tokens: promptTokens,
        completion_tokens: completionTokens,
        total_tokens: promptTokens + completionTokens,
      },
    };
  }
}

/** OpenAI's rule of thumb: about 4 characters per token for English text. */
export function estimateTokens(text: string): number {
  return Math.max(1, Math.ceil(text.length / 4));
}

function toAiCompletion(completion: OpenAiChatCompletion): AiCompletion {
  const answer = completion.choices[0]?.message.content;
  if (!answer) {
    throw new AiProviderUnavailableError('The mocked provider returned no choices.');
  }
  return {
    answer,
    promptTokens: completion.usage.prompt_tokens,
    completionTokens: completion.usage.completion_tokens,
    totalTokens: completion.usage.total_tokens,
    provider: 'openai-mock',
    model: completion.model,
  };
}
